info:
  app:
    name: @project.title@
    description: @project.description@
    encoding: @project.build.sourceEncoding@
    java.source: @java.version@
    java.target: @java.version@
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@

server:
  display-name: @project.title@
  port: ${PORT:8090}

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.
  health:
    mongo:
      enabled: true

#mongodb
spring:
  data:
    mongodb:
      host: ${DEMO_RS_DATASOURCE_HOST}
      port: ${DEMO_RS_DATASOURCE_PORT}
      database: ${DEMO_RS_DATASOURCE_DB}
      password: ${DEMO_RS_DATASOURCE_PASSWORD}
      username: ${DEMO_RS_DATASOURCE_USERNAME}
#  metrics:
#    export:
#      statsd:
#        prefix: rs-demo-${HOSTNAME}
#        host: ${DEMO_RS_METRICS_HOST}
#        port: ${DEMO_RS_METRICS_PORT}

#logging
logging:
  level:
    root: info
    org.springframework.data: info
    # org.springframework.boot.actuate.metrics: TRACE

#logstash
logstash:
  host: localhost
  port: 5000

#Keycloak
keycloak:
  auth-server-url: http://localhost:19010/auth
  realm: demo
  public-client: true
  resource: demo-resource-server
  principal-attribute: preferred_username