version: '2'
services:

  resource_server_mongo_admin:
    container_name: resource_server_mongo_admin
    image: mongo-express:0.38
    env_file:
     - ./docker-compose.env
    links:
      - "resource_server_mongo_db"
    ports:
      - "11001:8081"


  resource_server_mongo_db:
    container_name: resource_server_mongo_db
    image: mongo:latest
    env_file:
     - ./docker-compose.env
    ports:
      - "11002:27017"
    volumes:
      - "./data/dev-mongo:/data/db"
    command: mongod --auth
